/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRoundsRouteImport } from './routes/admin/rounds'
import { Route as AdminGrantsOverviewRouteImport } from './routes/admin/grants-overview'
import { Route as AdminCriteriaRouteImport } from './routes/admin/criteria'
import { Route as AdminAssessmentsRouteImport } from './routes/admin/assessments'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminRoundsIndexRouteImport } from './routes/admin/rounds/index'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin/applications/index'
import { Route as AdminRoundsIdRouteImport } from './routes/admin/rounds/$id'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin/applications/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoundsRoute = AdminRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrantsOverviewRoute = AdminGrantsOverviewRouteImport.update({
  id: '/grants-overview',
  path: '/grants-overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCriteriaRoute = AdminCriteriaRouteImport.update({
  id: '/criteria',
  path: '/criteria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssessmentsRoute = AdminAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoundsIndexRoute = AdminRoundsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoundsRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminApplicationsRoute,
} as any)
const AdminRoundsIdRoute = AdminRoundsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRoundsRoute,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminApplicationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/grants-overview': typeof AdminGrantsOverviewRoute
  '/admin/rounds': typeof AdminRoundsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/rounds/$id': typeof AdminRoundsIdRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/rounds/': typeof AdminRoundsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/grants-overview': typeof AdminGrantsOverviewRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/rounds/$id': typeof AdminRoundsIdRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/rounds': typeof AdminRoundsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/assessments': typeof AdminAssessmentsRoute
  '/admin/criteria': typeof AdminCriteriaRoute
  '/admin/grants-overview': typeof AdminGrantsOverviewRoute
  '/admin/rounds': typeof AdminRoundsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/rounds/$id': typeof AdminRoundsIdRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/rounds/': typeof AdminRoundsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/login'
    | '/admin/applications'
    | '/admin/assessments'
    | '/admin/criteria'
    | '/admin/grants-overview'
    | '/admin/rounds'
    | '/admin/users'
    | '/admin/'
    | '/admin/applications/$id'
    | '/admin/rounds/$id'
    | '/admin/applications/'
    | '/admin/rounds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/login'
    | '/admin/assessments'
    | '/admin/criteria'
    | '/admin/grants-overview'
    | '/admin/users'
    | '/admin'
    | '/admin/applications/$id'
    | '/admin/rounds/$id'
    | '/admin/applications'
    | '/admin/rounds'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/login'
    | '/admin/applications'
    | '/admin/assessments'
    | '/admin/criteria'
    | '/admin/grants-overview'
    | '/admin/rounds'
    | '/admin/users'
    | '/admin/'
    | '/admin/applications/$id'
    | '/admin/rounds/$id'
    | '/admin/applications/'
    | '/admin/rounds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rounds': {
      id: '/admin/rounds'
      path: '/rounds'
      fullPath: '/admin/rounds'
      preLoaderRoute: typeof AdminRoundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grants-overview': {
      id: '/admin/grants-overview'
      path: '/grants-overview'
      fullPath: '/admin/grants-overview'
      preLoaderRoute: typeof AdminGrantsOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/criteria': {
      id: '/admin/criteria'
      path: '/criteria'
      fullPath: '/admin/criteria'
      preLoaderRoute: typeof AdminCriteriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assessments': {
      id: '/admin/assessments'
      path: '/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAssessmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rounds/': {
      id: '/admin/rounds/'
      path: '/'
      fullPath: '/admin/rounds/'
      preLoaderRoute: typeof AdminRoundsIndexRouteImport
      parentRoute: typeof AdminRoundsRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminApplicationsRoute
    }
    '/admin/rounds/$id': {
      id: '/admin/rounds/$id'
      path: '/$id'
      fullPath: '/admin/rounds/$id'
      preLoaderRoute: typeof AdminRoundsIdRouteImport
      parentRoute: typeof AdminRoundsRoute
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminApplicationsRoute
    }
  }
}

interface AdminApplicationsRouteChildren {
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
}

const AdminApplicationsRouteChildren: AdminApplicationsRouteChildren = {
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
}

const AdminApplicationsRouteWithChildren =
  AdminApplicationsRoute._addFileChildren(AdminApplicationsRouteChildren)

interface AdminRoundsRouteChildren {
  AdminRoundsIdRoute: typeof AdminRoundsIdRoute
  AdminRoundsIndexRoute: typeof AdminRoundsIndexRoute
}

const AdminRoundsRouteChildren: AdminRoundsRouteChildren = {
  AdminRoundsIdRoute: AdminRoundsIdRoute,
  AdminRoundsIndexRoute: AdminRoundsIndexRoute,
}

const AdminRoundsRouteWithChildren = AdminRoundsRoute._addFileChildren(
  AdminRoundsRouteChildren,
)

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRouteWithChildren
  AdminAssessmentsRoute: typeof AdminAssessmentsRoute
  AdminCriteriaRoute: typeof AdminCriteriaRoute
  AdminGrantsOverviewRoute: typeof AdminGrantsOverviewRoute
  AdminRoundsRoute: typeof AdminRoundsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRouteWithChildren,
  AdminAssessmentsRoute: AdminAssessmentsRoute,
  AdminCriteriaRoute: AdminCriteriaRoute,
  AdminGrantsOverviewRoute: AdminGrantsOverviewRoute,
  AdminRoundsRoute: AdminRoundsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
